### ISSUE TITLE
bug:  Fix Card Dropdown UI Bug

### ISSUE THREAD

**Issue by DevonGifford** [mutaremalcolm/e-commerce-project#17]
#### **Description**:
  There is a small UI issue in the cart dropdown where the "Go to Checkout" button overflows its designated area. This creates a display problem for users trying to navigate to the checkout process.

#### **Actionable Items**:
  To resolve this issue, we need to make the following adjustments:
  - [x] Modify the styling to contain the "Go to Checkout" button within the cart dropdown area.
  - [x] Ensure responsiveness across various devices to guarantee the fix works universally.

### **Before Closing the Ticket**:
  Before considering this ticket resolved, we need to:
  - [x] Create and link a pull request for the changes that include the UI fix.
  - [x] Perform manual testing on different devices (desktop, mobile, tablet) to ensure the cart dropdown displays correctly and the button remains within its designated space.

---

This ticket aims to make a specific improvement to the cart dropdown UI by fixing the issue that causes the "Go to Checkout" button to overflow its designated area. It involves adjusting the styling and ensuring responsiveness across devices to provide users with a seamless shopping experience.

**Comment by mutaremalcolm** [comment]
Cart box also disappears on Safari and Mobile. Will resolve issue together with this one as they are related.

**Comment by mutaremalcolm** [comment]
Hopefully this is the appropriate link below:

https://deploy-preview-40--incomparable-dieffenbachia-18c4c9.netlify.app/
