### ISSUE TITLE
bug:  Logo Sizing Causing Layout Disturbance

### ISSUE THREAD

**Issue by DevonGifford** [mutaremalcolm/e-commerce-project#24]
#### Description:
The current logo sizing in the application is leading to disruptions in the layout, causing other elements to enlarge unexpectedly. This issue impacts the overall user interface and experience negatively.

#### Actionable Items:
- [x] **Investigate Logo Sizing Bug**:
  - [x] Analyze the CSS related to the logo for any unintended sizing or scaling properties.
  - [x] Identify the specific elements or components affected by the logo sizing issue.
- [x] **Implement Fixes**:
  - [x] Adjust the logo size to conform to standardized dimensions and prevent layout disturbances.
  - [x] Modify CSS rules or styles that impact the logo's size and its influence on other elements.
- [x] **Comprehensive Testing**:
  - [ ] Conduct thorough testing across different screen sizes and resolutions to ensure the logo sizing adjustments don't disrupt the layout or functionality elsewhere.
- [x] **Code Review**:
  - [x] Request a code review to confirm the changes don't introduce new issues and maintain the application's design consistency.
  
#### Before Closing the Ticket:
- [x] Confirm the logo displays correctly and consistently across various devices and screen sizes.
- [x] Verify with QA or team members that the logo size modifications have resolved the layout disturbance.
- [x] Document the changes made in the codebase for future reference and transparency.

**Comment by mutaremalcolm** [comment]
Hi Devon i have made relevant css adjustments to the logo.  Please review my code and see if the issue has been resolved. During testing i however picked up the box for the cart item seems to disappear when i open the site using Safari and on mobile. 

Will open a new issue item and work on it accordingly.

**Comment by DevonGifford** [comment]
Hi @mutaremalcolm  , please link the PR or commit.
